import { type NextPage } from "next";
import Head from "next/head";
import { useContractRead } from "wagmi";
import { useContext, useEffect, useState } from "react";
import FarmPool from "@/components/farm-pool";
import { ContractContext } from "@/contexts/ContractsProvider";
import masterChefABI from "@/utils/abi/masterChefABI.json";

const Home: NextPage = () => {

    const [poolInfo, setPoolInfo] = useState<number>();
    const [pools, setPools] = useState<number[]>();

    const { masterChef } = useContext(ContractContext);

    useContractRead(
        {
            address: masterChef,
            abi: masterChefABI,
            functionName: 'poolLength',
            onSuccess(data) {
                setPoolInfo(Number(data));
            }
        }
    );

    useEffect(() => {

        const arr = [];
        if (poolInfo != undefined) {
            for (let i = 0; i < poolInfo; i++) {
                arr.push(i);
            }
            setPools(arr);
        }
    }, [poolInfo]
    );

    return (
        <>
            <Head>
                <title>Axora Swap</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col h-3/4 overflow-y-hidden">

                <h2
                    className="scroll-m-20pb-2 text-3xl font-semibold tracking-tight transition-colors first:mt-0">
                    Yield Farm
                </h2>

                {
                    pools &&
                    <div className="flex flex-wrap gap-4 p-4 mt-4">
                        {pools.map((e) => {
                            return (
                                <FarmPool id={e} key={e} />
                            );
                        })}
                    </div>
                }
            </main>
        </>
    );
};




export default Home;