import { type PoolInfoType } from "@/components/farm-pool";
import { ContractContext } from "@/contexts/ContractsProvider";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useContext } from "react";
import { useContractRead } from "wagmi";
import masterChefABI from '@/utils/abi/masterChefABI.json';
import { type BigNumber } from "ethers";
import TokenDetails from '../../../components/tokenDetails';
import { Button } from "@/components/ui/button";

export type tokenData = {
    address: string;
    decimals: number;
    name: string;
    symbol: string;
    totalSupply: {
        formatted: string;
        value: BigNumber;
    };
};

const Home: NextPage = () => {

    const { poolID } = useRouter().query;
    const [poolInfo, setPoolInfo] = useState<PoolInfoType>();

    const { masterChef } = useContext(ContractContext);



    useContractRead({
        address: masterChef,
        abi: masterChefABI,
        functionName: "poolInfo",
        args: [poolID],
        onSuccess(data) {
            setPoolInfo(data as PoolInfoType);
        },
    },
    );



    return (
        <>
            <Head>
                <title>Axora Swap</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center h-3/4 overflow-y-hidden p-1 ">
                <div className="p-3 mt-10 rounded-lg ring-1 ring-slate-300 bg-white">
                    Yield Farm Pool {poolID}

                    {
                        poolInfo &&
                        <TokenDetails address={poolInfo.lpToken} />
                    }

                    
                </div>

                <div className="w-5/6 sm:w-96 p-3 mt-10 rounded-lg ring-1 ring-slate-300 bg-white">
                    <div className="flex flex-col gap-2 w-full mt-4">
                        <div className="flex w-full h-20 rounded-lg bg-slate-100 p-4 ring-1 ring-slate-200">
                            <input
                                className="outline-none bg-inherit text-2xl align-top"
                                placeholder="0"
                                pattern="^[0-9]*[.,]?[0-9]*$"

                            />
                            <div className="m-auto">
                                <h2 className="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-900 ring-1 ring-inset ring-green-900/20">ETH</h2>
                            </div>
                        </div>
                        <div className="relative m-auto" >

                            <div className="z-30 ring-2 ring-white bg-slate-300 rounded-xl p-1 -m-4">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-6 h-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12c0-1.232-.046-2.453-.138-3.662a4.006 4.006 0 00-3.7-3.7 48.678 48.678 0 00-7.324 0 4.006 4.006 0 00-3.7 3.7c-.017.22-.032.441-.046.662M19.5 12l3-3m-3 3l-3-3m-12 3c0 1.232.046 2.453.138 3.662a4.006 4.006 0 003.7 3.7 48.656 48.656 0 007.324 0 4.006 4.006 0 003.7-3.7c.017-.22.032-.441.046-.662M4.5 12l3 3m-3-3l-3 3" />
                                </svg>

                            </div>
                        </div>
                        <div className="flex w-full h-20 rounded-lg bg-slate-100 p-4 ring-1 ring-slate-200">
                            <input
                                className="outline-none bg-inherit text-2xl align-top"
                                placeholder="0"
                                pattern="^[0-9]*[.,]?[0-9]*$"
                            />
                            <div className="m-auto">
                                <h2 className="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-900 ring-1 ring-inset ring-green-900/20">asETH</h2>
                            </div>
                        </div>

                        <Button className="mt-4 ">Stake</Button>

                    </div>
                </div>
            </main>
        </>
    );

};

export default Home;