import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {

    return (
        <>
            <Head>
                <title>Axora Swap</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center h-3/4 overflow-y-hidden">
                <div className=" w-5/6 sm:w-96 p-3 mt-10 rounded-lg ring-1 ring-slate-300 bg-white">
                    FARM
                </div>
            </main>
        </>
    );

}

export default Home