// import { Button } from "@/components/ui/button";
// import { type NextPage } from "next";
// import Head from "next/head";

export default function Home() {
  return (
    <main>
      <div>Hello World</div>
    </main>
  );
}


// const Home: NextPage = () => {

//   return (
//     <>
//       <Head>
//         <title>Axora Finance</title>
//         <meta name="description" content="Generated by create-t3-app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className="flex min-h-screen flex-col items-center justify-center">
//         <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
//           <h2 className="scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors first:mt-0">
//             Axora Finance
//           </h2>
//           <Button>Hello</Button>
//         </div>
//       </main>
//     </>
//   );
// };




// export default Home;
