import { Button } from "@/components/ui/button";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    return(
        <>
        <Head>
                <title>Axora Pool</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <div className="flex justify-between">
                    <h2 className="scroll-m-20 pb-2 text-3xl  tracking-tight transition-colors first:mt-0 grow">
                        Top tokens on Axora
                        </h2>

                    
            </div>
                <table className="w-full bg-white rounded-lg ring-1 ring-slate-200">
                    <thead>
                        <tr className="m-0 p-0 even:bg-muted">
                            <th className=" p-4 font-light text-sm text-slate-600">
                                #
                            </th>
                            <th className=" p-4 font-light text-sm text-slate-600">
                                Token Name
                            </th>
                            <th className=" p-4  font-light text-sm text-slate-600">
                                Price
                            </th>
                            <th className=" p-4 font-light text-sm text-slate-600">
                                Change
                            </th>
                            <th className=" p-4 font-light text-sm text-slate-600">
                                TVL
                            </th>
                            <th className=" p-4 font-light text-sm text-slate-600">
                                Volume
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr className="m-0 p-0 even:bg-muted">
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Empty
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                        </tr>
                        <tr className="m-0 p-0 even:bg-muted">
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Empty
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                        </tr>
                        <tr className="m-0 p-0 even:bg-muted">
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Empty
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                        </tr>
                        <tr className="m-0 p-0 even:bg-muted">
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Empty
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                        </tr>
                        <tr className="m-0 p-0 even:bg-muted">
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Empty
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                        </tr>
                        <tr className="m-0 p-0 even:bg-muted">
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Empty
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                            <td className=" px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right">
                                Overflowing
                            </td>
                        </tr>

                    </tbody>
                </table>
        </main>
        </>
    )
}

export default Home;