import { ContractContext } from "@/contexts/ContractsProvider";
import { type NextPage } from "next";
import Head from "next/head";
import { useContext, useState } from "react";
import { useAccount, useBalance, useContractRead } from "wagmi";
import stakeABI from '@/utils/abi/stakingContractABI.json';
import FormStake from "@/components/form-stake";

const Home: NextPage = () => {

    const [myStakingBalance, setMyStakingBalance] = useState<number>(0);

    const { stakingContract } = useContext(ContractContext);
    const { address } = useAccount();
    useBalance({
        address,
        onSuccess(data){
            setMyETHBalance(data.formatted);
        }
    });

    const [myETHBalance , setMyETHBalance ] = useState<string>();

    useContractRead({
        address: stakingContract,
        abi: stakeABI,
        functionName: 'balanceOf',
        args: [address],
        onSuccess(data) {
            setMyStakingBalance(Number(data) / 10 ** 18);
        }
    });

    return (
        <>
            <Head>
                <title>Axora Swap</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center h-3/4 overflow-y-hidden p-2 text-center">
                {
                    address && 
                <div className="flex gap-4 ">
                    <div className="ring-1 ring-slate-200 bg-white p-4 rounded-lg">
                        <h3 className="text-xs font-semibold uppercase mx-auto">Stake Balance</h3>

                        <h2 className=" text-lg font-semibold">{myStakingBalance} asETH</h2>
                    </div>
                    <div className="ring-1 ring-slate-200 bg-white p-4 rounded-lg">
                        <h3 className="text-xs font-semibold uppercase mx-auto">Your Balance</h3>

                        <h2 className=" text-lg font-semibold">{myETHBalance?.slice(0,8)} ETH</h2>
                    </div>
                </div>
                }
                <div>
                    <FormStake />
                </div>
            </main>
        </>
    );
};




export default Home;