import { Button } from "@/components/ui/button";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    return(
        <>
        <Head>
                <title>Axora Pool</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <div className="flex justify-between">
                    <h2 className="scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight transition-colors first:mt-0 grow">
                        Pools
                        </h2>

                    <Button>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-5 h-5">
                            <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
                        </svg>

New Position
</Button>
            </div>
        </main>
        </>
    )
}

export default Home;